### ISSUE TITLE
Only switch is exposed

### ISSUE THREAD

**Issue by NainRouge** [kurtwarwick-new/homebridge-appletv-now-playing#10]
This plugin is only creating a non functional power state switch.

There is no Playback State or Now Playing Information.

Config:
{
            "platform": "AppleTvNowPlayingPlatform",
            "debug": true,
            "devices": [
                {
                    "name": "Da Apple TV",
                    "credentials": "B794AF12-xxxx-xxxx-xxxx-......"
                }
            ]
        }

**Comment by kurtwarwick-new** [comment]
Hi @NainRouge 

This is how the native HomeKit app works. Because I am exposing custom characteristics, they will not show in the Home App. If you want to use the states, you will need to use the Home+ or Eve app, where the extra characteristics can be used.

For example, the Home+ 4 App.

![image](https://user-images.githubusercontent.com/61435184/83252713-0810ff80-a1ac-11ea-9120-e642f70aa406.png)

I will be updating the readme to include this information.

Thanks.

Kurt
