### ISSUE TITLE
On/off status while airplaying

### ISSUE THREAD

**Issue by adamrzanek** [kurtwarwick-new/homebridge-appletv-now-playing#16]
It’s working great until I’m Air playing from my Apple TV to my HomePod.

**Comment by kurtwarwick-new** [comment]
Hi @adamrzanek 

Unfortunately, the library I am using to get the information from the Apple TV currently only supports the Apple TV and not AirPlay status. I don't see any plans to add this kind of support, and since I don't have this particular use case (my house if filled with Google Homes), I don't think I will be spending time looking into this in the near future.

I hope you undertsand.

Kind regards

Kurt
