### ISSUE TITLE
TV Status

### ISSUE THREAD

**Issue by maxphour** [kurtwarwick-new/homebridge-appletv-now-playing#19]
Hi, 
first of all I really appreciate how well the plugin displays the actual status of the AppleTV.
I've included the AppleTV switch in my Good Night Scene to turn off the TV when I'm going to bed. 
The Problem: If I trigger the Good Night Scene and the TV is off it turns on. Is there any chance to change this?

Thanks

Max

**Comment by kurtwarwick-new** [comment]
Hi @maxphour 

Could you kindly check that your scene is not perhaps toggling the Apple TV accessory? I think you need to alter your scene to turn it off and not toggle it. 

There otherwise isn't anything I can do further to change this behavior since it's simply a switch.

I hope that helps!

Please let me know.

Regards

Kurt

**Comment by maxphour** [comment]
Hi Kurt, 
thanks for the quick reply. 
In the scene the tv turns off. But anyway, I got a quick workaround, not for scenes, but for automations. Works fine for me at least.

**Comment by kurtwarwick-new** [comment]
Hi @maxphour 

I have just found a potential fix for this issue and I will push out a fix for it soon.

Regards

Kurt

**Comment by kitsen13** [comment]
Hello, any news?

Thanks

**Comment by LordZork** [comment]
@kitsen13 (or anyone willing to help) sorry, don't mean to hijack this issue, but how do you even get past the "retrieve credentials" step?  Not sure how to figure out the path to use (from the instructions, below)?

"In order to retrieve credentials for your Apple TV, please follow these step

Execute the cli application bundled with this package from the package directory
`/path/to/homebridge-appletv-now-playing $ node .\bin\cli.js`"

As of this writing, I'm running the latest **Homebridge** and **Homebridge Config UI X**, on the latest **Raspberry Pi 4**. And, I'm fairly new to Homebridge – no idea how to find the correct path to use for the code (above).

https://github.com/kurtwarwick-new/homebridge-appletv-now-playing/issues/20

**Comment by kurtwarwick-new** [comment]
Hi @maxphour , @kitsen13 

Apologies for the AWOL status. I have been distracted from this project with someone in my family having contracted COVID-19 and having to deal with all of that, along with having a rather huge amount of work from my day-job.

I have been working on this on and off and I have fixed this particular bug. I am hoping to merge it in soon.

Thanks for understanding!

@LordZork 

I have responded to your issue, and hopefully you should come right. However, as I have stated there, please let me know if you need any further help.

Regards

Kurt

**Comment by kurtwarwick-new** [comment]
Hi

I have merged this change in and should hopefully fix up this issue.

Please could you verify by updating your plugin?

Thanks.

Kurt

**Comment by maxphour** [comment]
Hi @kurtwarwick-new,
I updated the plugin and the issue is fixed. But I noticed another bug (I'm pretty sure it is one). I can't turn the AppleTV off via the Home-App anymore. It looks like instead of a long press on the TV Button and then a single press to turn it off the plugin just executes a short press on the TV Button. Only if I double press the TV Switch in the Home App it turns off, but that does not work with scenes or with Siri. 

Regards 

Max

**Comment by kitsen13** [comment]
@kurtwarwick-new no problem man, thanks for your job

**Comment by kurtwarwick-new** [comment]
@maxphour 

Indeed it is a bug! It was due to a typo when fixing up another issue. I have just updated the plugin with a fix...

Please update and try again?

Thanks!

**Comment by maxphour** [comment]
Hi @kurtwarwick-new, 
works great now. Thank you so much man! 
All the best to you!
